name: vm_service_client
version: 1.0.0-dev
description: A client for the Dart VM service.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_client

environment:
  sdk: '>=1.12.0 <2.0.0'

dev_dependencies:
  test: '^0.12.0'
