name: vm_service_client
version: 0.0.1-dev
description: A client for the Dart VM service.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_client

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  async: '^1.3.0'
  collection: '>=0.9.2 <2.0.0'
  json_rpc_2: '^1.2.0'
  pub_semver: '^1.0.0'

dev_dependencies:
  test: '^0.12.0'
